image:
- Ubuntu

skip_branch_with_pr: true
stack: python 3.10

environment:
  GITHUB_TOKEN:
    secure: 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

install:
- pip install -r requirements.txt

build_script:
- flet pack main.py --name counter --icon icon.png --product-name counter --product-version "1.2.3" --copyright "Copyright (c) 2022 YourCompany Inc."

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: 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
  on:
    APPVEYOR_REPO_TAG: true


#
#   Linux package
#
for:
-
  matrix:
    only:
    - image: Ubuntu

  after_build:
  - tar -czvf counter-linux.tar.gz -C dist counter

  artifacts:
  - path: counter-linux.tar.gz